#!/usr/bin/env python3
"""Preview or apply a reversible source-owned skill exposure profile."""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import stat
import tomllib
from datetime import datetime, timezone
from pathlib import Path


BEGIN = "# BEGIN agent-skills managed exposure"
END = "# END agent-skills managed exposure"


def fail(message: str) -> None:
    raise SystemExit(message)


def read_profile(path: Path) -> list[str]:
    if not path.is_file():
        fail(f"profile not found: {path}")
    names: list[str] = []
    seen: set[str] = set()
    for raw in path.read_text(encoding="utf-8").splitlines():
        name = raw.strip()
        if not name or name.startswith("#"):
            continue
        if name in seen:
            fail(f"duplicate skill in profile {path}: {name}")
        seen.add(name)
        names.append(name)
    return names


def source_skills(root: Path) -> dict[str, Path]:
    skills_root = root / "skills"
    if not skills_root.is_dir():
        fail(f"skills root not found: {skills_root}")
    return {
        path.name: path.resolve()
        for path in sorted(skills_root.iterdir())
        if path.is_dir() and (path / "SKILL.md").is_file()
    }


def strip_managed_block(text: str) -> str:
    begins = text.count(BEGIN)
    ends = text.count(END)
    if begins != ends or begins > 1:
        fail("config has an incomplete or duplicate managed exposure block")
    if not begins:
        return text
    start = text.index(BEGIN)
    finish = text.index(END, start) + len(END)
    before = text[:start].rstrip()
    after = text[finish:].lstrip("\n")
    parts = [part for part in (before, after.rstrip()) if part]
    return "\n\n".join(parts) + ("\n" if parts else "")


def parse_toml(text: str, label: str) -> dict:
    try:
        return tomllib.loads(text) if text.strip() else {}
    except tomllib.TOMLDecodeError as exc:
        fail(f"invalid TOML in {label}: {exc}")


def normalized_path(value: str) -> Path:
    return Path(value).expanduser().resolve(strict=False)


def reject_manual_source_overrides(base_text: str, skills: dict[str, Path]) -> None:
    data = parse_toml(base_text, "config outside the managed block")
    known = {(path / "SKILL.md").resolve(strict=False) for path in skills.values()}
    entries = data.get("skills", {}).get("config", [])
    if not isinstance(entries, list):
        fail("skills.config must be an array of tables")
    conflicts: list[str] = []
    for entry in entries:
        if not isinstance(entry, dict) or not isinstance(entry.get("path"), str):
            continue
        if normalized_path(entry["path"]) in known:
            conflicts.append(entry["path"])
    if conflicts:
        fail("source-owned skill override exists outside managed block: " + ", ".join(conflicts))


def managed_block(skills: dict[str, Path], enabled: set[str]) -> str:
    lines = [BEGIN, "# Generated by scripts/apply-skill-profile.py; do not edit this block."]
    for name, path in skills.items():
        lines.extend(
            [
                "",
                "[[skills.config]]",
                f"path = {json.dumps(str(path / 'SKILL.md'))}",
                f"enabled = {'true' if name in enabled else 'false'}",
            ]
        )
    lines.extend(["", END])
    return "\n".join(lines) + "\n"


def render_config(current: str, skills: dict[str, Path], enabled: set[str]) -> str:
    base = strip_managed_block(current)
    reject_manual_source_overrides(base, skills)
    rendered = (base.rstrip() + "\n\n" if base.strip() else "") + managed_block(skills, enabled)
    parse_toml(rendered, "generated config")
    return rendered


def digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def atomic_write(path: Path, data: bytes, mode: int = 0o600) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temp = path.with_name(f".{path.name}.tmp-{os.getpid()}")
    if temp.exists() or temp.is_symlink():
        fail(f"temporary path already exists: {temp}")
    try:
        with temp.open("xb") as handle:
            handle.write(data)
            handle.flush()
            os.fsync(handle.fileno())
        temp.chmod(mode)
        os.replace(temp, path)
    finally:
        if temp.exists():
            temp.unlink()


def is_expected_link(path: Path, source: Path) -> bool:
    return path.is_symlink() and path.resolve(strict=False) == source


def preflight_links(dest_root: Path, skills: dict[str, Path], enabled: set[str]) -> list[str]:
    to_link: list[str] = []
    for name in sorted(enabled):
        destination = dest_root / name
        if is_expected_link(destination, skills[name]):
            continue
        if destination.exists() or destination.is_symlink():
            fail(f"refusing to replace existing destination: {destination}")
        to_link.append(name)
    return to_link


def write_record(path: Path, record: dict) -> None:
    payload = (json.dumps(record, indent=2, sort_keys=True) + "\n").encode()
    atomic_write(path, payload)


def apply_profile(
    config_path: Path,
    dest_root: Path,
    record_dir: Path,
    rendered: str,
    skills: dict[str, Path],
    enabled: set[str],
    profile_name: str,
) -> None:
    if config_path.is_symlink():
        fail(f"refusing to replace symlinked config: {config_path}")
    config_existed = config_path.exists()
    before = config_path.read_bytes() if config_existed else b""
    after = rendered.encode()
    to_link = preflight_links(dest_root, skills, enabled)
    if before == after and not to_link:
        print("no changes required")
        return

    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S%fZ")
    record_dir.mkdir(parents=True, exist_ok=True)
    record_dir.chmod(0o700)
    backup = record_dir / f"skill-profile-{stamp}.config.before"
    record_path = record_dir / f"skill-profile-{stamp}.json"
    atomic_write(backup, before)
    record = {
        "version": 1,
        "profile": profile_name,
        "timestamp_utc": datetime.now(timezone.utc).isoformat(),
        "config_path": str(config_path),
        "config_existed": config_existed,
        "backup_path": str(backup),
        "before_sha256": digest(before),
        "after_sha256": digest(after),
        "dest_root": str(dest_root),
        "linked": to_link,
        "linked_targets": {name: str(skills[name]) for name in to_link},
        "enabled": sorted(enabled),
        "disabled": sorted(set(skills) - enabled),
    }
    write_record(record_path, record)

    mode = stat.S_IMODE(config_path.stat().st_mode) if config_path.exists() else 0o600
    linked: list[Path] = []
    try:
        atomic_write(config_path, after, mode)
        dest_root.mkdir(parents=True, exist_ok=True)
        for name in to_link:
            destination = dest_root / name
            os.symlink(skills[name], destination)
            linked.append(destination)
    except Exception:
        for destination in reversed(linked):
            if destination.is_symlink():
                destination.unlink()
        if config_existed:
            atomic_write(config_path, before, mode)
        elif config_path.exists():
            config_path.unlink()
        raise
    print(f"action_record={record_path}")


def restore(record_path: Path, apply: bool) -> int:
    record = json.loads(record_path.read_text(encoding="utf-8"))
    if record.get("version") != 1:
        fail("unsupported action record version")
    config_path = Path(record["config_path"])
    backup_path = Path(record["backup_path"])
    current = config_path.read_bytes() if config_path.exists() else b""
    before = backup_path.read_bytes()
    if digest(current) != record["after_sha256"]:
        fail("current config differs from the recorded applied state; refusing restore")
    if digest(before) != record["before_sha256"]:
        fail("backup checksum mismatch; refusing restore")
    dest_root = Path(record["dest_root"])
    linked = [dest_root / name for name in record.get("linked", [])]
    targets = record.get("linked_targets", {})
    for path in linked:
        expected = Path(targets.get(path.name, ""))
        if not is_expected_link(path, expected):
            fail(f"recorded link changed after apply: {path}")
    print(f"restore_record={record_path}")
    print(f"unlink={len(linked)} restore_config=yes")
    if not apply:
        print("dry-run only; no files changed")
        return 0
    for path in linked:
        path.unlink()
    if record["config_existed"]:
        mode = stat.S_IMODE(config_path.stat().st_mode) if config_path.exists() else 0o600
        atomic_write(config_path, before, mode)
    elif config_path.exists():
        config_path.unlink()
    print("restore complete")
    return 0


def main() -> int:
    repo_default = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--profile", action="append", help="Profile name or path; repeat to combine")
    parser.add_argument("--enable", action="append", default=[], help="Enable one additional source-owned skill")
    parser.add_argument("--disable", action="append", default=[], help="Disable one skill from the selected profiles")
    parser.add_argument("--restore-record", help="Reverse a prior apply record")
    parser.add_argument("--repo-root", default=str(repo_default))
    parser.add_argument("--dest-root", default=str(Path.home() / ".codex" / "skills"))
    parser.add_argument("--config-path", default=str(Path.home() / ".codex" / "config.toml"))
    parser.add_argument("--record-dir", default=str(Path.home() / ".AGENTS-temp" / "agent-skills" / "profile-apply"))
    parser.add_argument("--apply", action="store_true", help="Apply; default is dry-run")
    args = parser.parse_args()

    if args.restore_record:
        if args.profile or args.enable or args.disable:
            fail("restore cannot be combined with profile changes")
        return restore(Path(args.restore_record).expanduser(), args.apply)
    if not args.profile:
        fail("provide at least one --profile")

    repo_root = Path(args.repo_root).expanduser().resolve()
    profiles_root = repo_root / "profiles"
    skills = source_skills(repo_root)
    enabled_order: list[str] = []
    profile_names: list[str] = []
    for item in args.profile:
        path = Path(item).expanduser()
        if not path.exists():
            path = profiles_root / f"{item}.txt"
        profile_names.append(path.stem)
        for name in read_profile(path):
            if name not in enabled_order:
                enabled_order.append(name)
    requested = set(enabled_order) | set(args.enable) | set(args.disable)
    unknown = sorted(requested - set(skills))
    if unknown:
        fail("unknown skills: " + ", ".join(unknown))
    overlap = sorted(set(args.enable) & set(args.disable))
    if overlap:
        fail("skills cannot be both enabled and disabled: " + ", ".join(overlap))
    enabled = (set(enabled_order) | set(args.enable)) - set(args.disable)

    config_path = Path(args.config_path).expanduser()
    current = config_path.read_text(encoding="utf-8") if config_path.exists() else ""
    rendered = render_config(current, skills, enabled)
    to_link = preflight_links(Path(args.dest_root).expanduser(), skills, enabled)
    disabled = sorted(set(skills) - enabled)
    print(f"profile={'+'.join(profile_names)}")
    print(f"mode={'apply' if args.apply else 'dry-run'} enabled={len(enabled)} disabled={len(disabled)} link={len(to_link)}")
    for name in sorted(enabled):
        print(f"ENABLE  {name}")
    for name in disabled:
        print(f"DISABLE {name}")
    for name in to_link:
        print(f"LINK    {name}")
    if not args.apply:
        print("dry-run only; no files changed")
        return 0
    apply_profile(
        config_path,
        Path(args.dest_root).expanduser(),
        Path(args.record_dir).expanduser(),
        rendered,
        skills,
        enabled,
        "+".join(profile_names),
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
